# [作業目標]

1. [簡答題] 請問 type(...) 跟 a.dtype 這兩個語法有什麼不同？

```
print('type(a): ', type(a))
print('a.dtype: ', a.dtype)
```

2. 請撰寫一個判斷 a 的元素是否等於指定資料型態的函式

3. [簡答題] 承上題，請判斷下列三種寫法為何不正確？

```
def is_dtype(a, t):
    return a.dtype is t

def is_dtype(a, t):
    return type(a) == np.dtype(t)

def is_dtype(a, t):
    return type(a) is np.dtype(t)
```

# 作業 

### 1. [簡答題] 請問 type(...) 跟 a.dtype 這兩個語法有什麼不同？

```
print('type(a): ', type(a))
print('a.dtype: ', a.dtype)
```


In [13]:
print('type(a): ', type(a)) #type(a):  <class 'numpy.ndarray'>
print('a.dtype: ', a.dtype) #a.dtype:  int32

type(a):  <class 'numpy.ndarray'>
a.dtype:  int32


type(a)是回傳a變數的型態=>用於變數的型態，會傳array
a.dtype是回傳a陣列中的元素型態

### 2. 請撰寫一個判斷 a 的元素是否等於指定資料型態的函式，並且通過測試。



In [11]:
# 記得先 Import 正確的套件

import numpy as np



a = np.arange(15).reshape(3,5)

print(a)
print(a.dtype == 'int32')
print(a.dtype == np.int32)
print(a.dtype is np.dtype('int32'))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
True
True
True


In [14]:
def is_dtype(a, t):
    return a.dtype is np.dtype(t)

In [20]:
a = np.random.randint(10, size=6) 

# 測試一
print(is_dtype(a, 'int')) # True

# 測試二
#print(is_dtype(a, np.int)) # True
#由於 NumPy 1.20 版本中 np.int 別名被移除所致。
#在 NumPy 1.20 之後，np.int 不再存在，而是建議直接使用 Python 內建的 int 關鍵字。

# 測試三
print(is_dtype(a, np.dtype('int'))) # True



True
True


In [19]:
import numpy as np

def is_dtype(a, t):
    return a.dtype is np.dtype(t)

a = np.random.randint(10, size=6) 

# 測試一
print(is_dtype(a, 'int'))  # True

# 測試二
print(is_dtype(a, int))  # True

# 測試三
print(is_dtype(a, np.dtype('int')))  # True



True
True
True


### 3. [簡答題] 承上題，請判斷下列三種寫法為何不正確？

```
def is_dtype(a, t):
    return a.dtype is t

def is_dtype(a, t):
    return type(a) == np.dtype(t)

def is_dtype(a, t):
    return type(a) is np.dtype(t)
```

type() 是檢查變數的型態，而不是元素的型態；
is 相對 == 更嚴格，一定要型態都正確才會回傳True

In [17]:
"""
變數（Variable）：

變數是用來存儲和表示數據的名稱。
在程式中，你可以使用變數來存儲各種數據，包括數字、字串、列表、物件等。
變數是內存中的一個位置，你可以通過給它一個名稱來引用這個位置，以便後續使用。
"""
x = 5  # 在這裡，x 是一個變數，存儲了整數 5
name = "John"  # 在這裡，name 是一個變數，存儲了字串 "John"


In [ ]:
"""
元素（Element）：

元素通常用來描述在數組、列表、集合、字典等數據結構中的單個數據項。
在這種上下文中，元素是這些數據結構中的個別部分，它們可以是任何類型的數據，包括數字、字串、對象等。
例如，在列表中，每個元素都是列表的一個項目。
"""
numbers = [1, 2, 3, 4, 5]  # 在這裡，列表 numbers 有五個元素：1, 2, 3, 4, 5
