# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


list(a) 只會把第一層的元素轉換成 List，多層的話只有第一層會轉；

tolist() 才能達成多層的型態轉換

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [27]:
# 記得先 Import 正確的套件
import numpy as np



In [28]:

a = np.random.randint(10, size=6) 
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(a.data)
print("""""")
#python內建查詢length、type的方法
print(len(a))
print(type(a))

[0 1 4 8 3 2]
1
(6,)
6
int32
4

6
<class 'numpy.ndarray'>


array a 為
一維、
維度形狀1*6=>行*列
陣列中6個元素、
資料型態為int64(整數)=>type
長度為4=>lengh


In [29]:
b = np.random.randint(10, size=(3,4)) 
print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print("""""")
print(len(b))
print(type(b))

[[0 5 9 5]
 [4 5 4 5]
 [6 6 4 0]]
2
(3, 4)
12
int32
4

3
<class 'numpy.ndarray'>


array b 為
二維、
維度形狀3*4=>行*列
陣列中12個元素、
資料型態為int32(整數)
長度為4

長度變成3


In [30]:
c = np.random.randint(10, size=(2,3,2)) 

print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)

print("""""")
print(len(c))
print(type(c))

[[[3 2]
  [8 2]
  [6 1]]

 [[9 8]
  [1 4]
  [7 2]]]
3
(2, 3, 2)
12
int32
4

2
<class 'numpy.ndarray'>


array b 為
三維、
維度形狀2*3*2=>行*列*高
陣列中12個元素、
資料型態為int32(整數)=>type
長度為4=>lengh

a.size：

a.size 返回 NumPy 數組 a 的總元素數量，即所有維度上的元素個數的乘積。 對於多維數組，a.size 返回的是所有維度元素的總數。 例如，如果 a 是一個 2x3 的矩陣，a.size 將返回 6。

len(a)：

len(a) 返回的是 NumPy 數組 a 的第一個維度的元素個數。 對於多維數組，len(a) 只返回第一個維度的元素數量。 例如，如果 a 是一個 2x3 的矩陣，len(a) 將返回 2。 簡而言之，a.size 考慮了所有維度上的元素，而 len(a) 只關心第一個維度的元素個數。在處理多維數組時，要注意這兩者之間的區別。如果 a 是一維數組，則 a.size 和 len(a) 將返回相同的結果。

### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [31]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[6, 5, 4, 1, 0, 5]
[6, 5, 4, 1, 0, 5]


In [32]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[6, 7, 0, 8], [9, 3, 3, 9], [5, 3, 7, 8]]
[array([6, 7, 0, 8]), array([9, 3, 3, 9]), array([5, 3, 7, 8])]


In [33]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[7, 7], [8, 7], [5, 8]], [[5, 0], [9, 4], [7, 5]]]
[array([[7, 7],
       [8, 7],
       [5, 8]]), array([[5, 0],
       [9, 4],
       [7, 5]])]


In [37]:
#簡單版
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    newlist = []
    for obj in iterable:
        newlist.append(tolist(obj))
    return list(newlist)
    
print(tolist(a))
print(tolist(b))
print(tolist(c))

[6, 5, 4, 1, 0, 5]
[[6, 7, 0, 8], [9, 3, 3, 9], [5, 3, 7, 8]]
[[[7, 7], [8, 7], [5, 8]], [[5, 0], [9, 4], [7, 5]]]


In [39]:
#進階版
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    return [tolist(obj) for obj in iterable]
    
print(tolist(a))
print(tolist(b))
print(tolist(c))

[6, 5, 4, 1, 0, 5]
[[6, 7, 0, 8], [9, 3, 3, 9], [5, 3, 7, 8]]
[[[7, 7], [8, 7], [5, 8]], [[5, 0], [9, 4], [7, 5]]]


做一個小迴圈把list一層一層寫進去
將 NumPy 數組轉換為列表